### ISSUE TITLE
TFMongoDB release 1.3 

### ISSUE THREAD

**Issue by sindbach** [svenboesiger/tfmongodb#3]
Hi @svenboesiger , 
Would you be able to do a release of TFMongoDB v1.3 to PyPi ? 
Please let me know if there's any other issues blocking this 

Regards, 
Wan.

**Comment by mahmoudakl** [comment]
Hey @sindbach,

I saw your commits on getting this to work under Linux as well. Is there any documentation on how to install it?

Best,
Mahmoud

**Comment by svenboesiger** [comment]
Hi @mahmoudakl 

I added a guide how to build the library on Linux in the README.md.

Cheers,
Sven
